### ISSUE TITLE
Custom brand color no longer works in Ember CLI 3.13

### ISSUE THREAD

**Issue by barryofguilder** [ember-learn/ember-cli-addon-docs#407]
I just upgraded my addon from Ember CLI 3.12 to 3.13 and the custom brand color is no longer working. It seems there's something strange going on in the CSS backing it.

This screenshot is on Ember CLI 3.12 (works):
<img width="562" alt="Screen Shot 2019-10-07 at 4 19 46 PM" src="https://user-images.githubusercontent.com/5649106/66346360-02fef780-e920-11e9-8bcc-1da350dee1bc.png">

And here is Ember CLI 3.13 (doesn't work):
<img width="562" alt="Screen Shot 2019-10-07 at 4 21 03 PM" src="https://user-images.githubusercontent.com/5649106/66346370-08f4d880-e920-11e9-9524-4a2fdbcf5db4.png">

**Comment by barryofguilder** [comment]
The workaround for now (for our addon anyways) was to add the following to our `app.css` file in our dummy app:

```css
.docs-bg-brand {
  background-color: #e04e39 !important;
}
.docs-text-brand {
  color: #e04e39 !important;
}
```
